# Generated by Django 2.2.6 on 2019-11-03 23:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0002_auto_20191104_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='invited',
            field=models.ManyToManyField(related_name='invited_user', to=settings.AUTH_USER_MODEL, verbose_name='Приглашенные участники'),
        ),
    ]
